version: "3.9"

services:
  removebg:
    container_name: removebg_api_v2
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - WORKERS=4
      - TIMEOUT=120
      - PYTHONUNBUFFERED=1
    command: >
      gunicorn -w ${WORKERS:-4}
               -k gevent
               --worker-connections 100
               -b 0.0.0.0:5000
               --timeout ${TIMEOUT:-120}
               app:app
